### PR TITLE
Add workaround implementation of 'where' function

### PR DESCRIPTION
**Pull request by msakai**
This adds a workaround implementation of `F.where` function.

This implementation approximates `F.where(cond, x1, x2)` as `(cond * x1) + ((1-cond) * x2)`, but its behavior on NaN and infinities are different.

Note that I couldn't find a way to generate fresh names so that I resorted to define dumb `gensym` function.

### CODE REVIEW

**Comment by msakai** [comment]
I fixed the checker error in a ad-hoc way.
But now I encounter the following `onnxruntime` error.

> RuntimeError: Method run failed due to: [LotusError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime11NonOnnxTypeIbEE) , expected: (N11onnxruntime11NonOnnxTypeIfEE)

**Comment by msakai** [comment]
`N11onnxruntime11NonOnnxTypeIbEE` and `N11onnxruntime11NonOnnxTypeIfEE` are mangled name of `onnxruntime::NonOnnxType<bool>` and `onnxruntime::NonOnnxType<float>` respectively.

**Comment by disktnk** [comment]
Add `F.where` converter #142 . ONNX `Where` operator is added from opset=9 https://github.com/onnx/onnx/blob/master/docs/Operators.md#where

**Comment by disktnk** [comment]
This workaround looks nice, but currently ONNX support `Where` operator, so I close this PR, thank you. If we'll get a requirement to execute `where` function under opset<=8, we'll re-consider about supporting.

**Pull request closed without merging**
