### PR TITLE
support AddConstant

### PR DESCRIPTION
**Pull request by msakai**
This adds `AddConstant` support.
The implementation is identical to `PowVarConst`.

### CODE REVIEW

**Comment by mitmul** [comment]
@msakai Thank you for the PR! Could you add a test for it?

**Comment by msakai** [comment]
Okay.
I skipped writing a test case because I was not familiar with `unittest` module, but I'll give it a try 💪.

**Comment by msakai** [comment]
I added a test case in `tests/functions_tests/test_maths.py`.

**Comment by msakai** [comment]
@mitmul Could you review it if you have spare time?

**Comment by mitmul** [comment]
LGTM

**Pull request merged**
